adding finesse search results to expand search examples
ai-cfia/finesse-data pull request #2
Opened 2023-11-21 20:14 UTC by melanie-fressard

issue #1

2023-11-21 20:35 UTC, k-allagbe approved these changes

2023-11-21 22:23 UTC, rngadam requested changes
One of the cases where we want to keep the whitespaces actually as the name of the file is what gets displayed in the finesse-frontend by @CFIALeronB static results testing utility.

2023-11-22 14:30 UTC, melanie-fressard commented
> One of the cases where we want to keep the whitespaces actually as the name of the file is what gets displayed in the finesse-frontend by @CFIALeronB static results testing utility.

Oh, didn't know that, I'm changing this !

2023-11-22 20:40 UTC, rngadam approved these changes

2023-11-22 21:41 UTC, merged